// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'SUA-CHAVE-AQUI',
    appId: '1:207514228109:web:d6f67127f6dd9bf609d9c4',
    messagingSenderId: '207514228109',
    projectId: 'aula-flutter-d9a98',
    authDomain: 'aula-flutter-d9a98.firebaseapp.com',
    storageBucket: 'aula-flutter-d9a98.appspot.com',
    measurementId: 'G-R2XNR4Q6X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'SUA-CHAVE-AQUI',
    appId: '1:556689954652:android:ebf638d01391c09fba5399',
    messagingSenderId: '556689954652',
    projectId: 'crud-b23f3',
    storageBucket: 'crud-b23f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'SUA-CHAVE-AQUI',
    appId: '1:556689954652:ios:c3b9a312b4cc6bc1ba5399',
    messagingSenderId: '556689954652',
    projectId: 'crud-b23f3',
    storageBucket: 'crud-b23f3.appspot.com',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'SUA-CHAVE-AQUI',
    appId: '1:556689954652:ios:c3b9a312b4cc6bc1ba5399',
    messagingSenderId: '556689954652',
    projectId: 'crud-b23f3',
    storageBucket: 'crud-b23f3.appspot.com',
    iosBundleId: 'com.example.crudapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'SUA-CHAVE-AQUI',
    appId: '1:556689954652:web:f446ba4177fd0e55ba5399',
    messagingSenderId: '556689954652',
    projectId: 'crud-b23f3',
    authDomain: 'crud-b23f3.firebaseapp.com',
    storageBucket: 'crud-b23f3.appspot.com',
  );
}
